### ISSUE TITLE
Jenkins is no longer forking (--daemon has been removed)

### ISSUE THREAD

**Issue by seidler2547** [voxpupuli/puppet-jenkins#1024]
As per Jenkins 2.313, the `--daemon` parameter [has been removed from Jenkins](https://github.com/jenkinsci/jenkins/pull/5561#issuecomment-922331425).

That means that systemd does not consider the service to be fully started anymore since it never forks.

The fix is to remove the `Type=forking` line from the systemd service, and also remove the `PARAMS+=("--daemon")` line from the the jenkins-run file.

**Comment by smortex** [comment]
Have you considered opening a Pull Request (PR) to add your change :wink:? This look like a perfect enhancement for a first-time contributor!

If you do not know how to start, here is a quite complete guide about the process of contributing to projects on GitHub:
https://dataschool.io/how-to-contribute-on-github

In any case, do not feel scared: we are here to help!

**Comment by ekohl** [comment]
This was resolved in https://github.com/voxpupuli/puppet-jenkins/pull/1025.
