### ISSUE TITLE
Support for Jenkins < 2.332

### ISSUE THREAD

**Issue by Joris29** [voxpupuli/puppet-jenkins#1042]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.25.1
- Ruby: /
- Distribution: RHEL 8
- Module version: Master

## How to reproduce (e.g Puppet code you use)
```puppet
class { 'jenkins':
    version           => $version,
    repo              => false,
    lts               => $lts,
    proxy_host        => $profile::globals::proxy_host,
    proxy_port        => $profile::globals::proxy_port,
    no_proxy_list     => $_noproxy,
    localstatedir     => $profile::jenkins::home,
    manage_datadirs   => false,
    manage_user       => false,
    manage_group      => false,
    cli_username      => 'user1',
    cli_password_file => '/var/passfile',
    slaveagentport    => 99999,
    config_hash       => {
      'JENKINS_HOME' => { 'value' => $profile::jenkins::home },
    },
  }
```

## What are you seeing
Jenkins service not starting

## What behaviour did you expect instead
That the service would start

## Output log
```
Error: Systemd start for jenkins failed!
journalctl log for jenkins:
-- Logs begin at Mon 2021-05-03 15:28:28 CEST, end at Fri 2022-05-13 18:41:36 CEST. --
-- No entries --

Error: /Stage[main]/Jenkins::Service/Service[jenkins]/ensure: change from 'stopped' to 'running' failed: Systemd start for jenkins failed!
journalctl log for jenkins:
-- Logs begin at Mon 2021-05-03 15:28:28 CEST, end at Fri 2022-05-13 18:41:36 CEST. --
-- No entries --
 (corrective)
```

**Comment by ekohl** [comment]
For my understanding: why do you want support for < 2.332? That's older than what's in the current LTS repositories, which makes it unsupported from an upstream perspective.

It's my intention to release a 3.0.0 soon which simply takes 2.332 as the minimum version. Getting the module even in a working state with the current version has been hard enough so I'm leaning to closing this as WONTFIX. If you need < 2.332 support, pin your module to an older version.
