### ISSUE TITLE
The module should support FreeBSD 10 and pkgng

### ISSUE THREAD

**Issue by rtyler** [voxpupuli/puppet-jenkins#105]
I figure that at the very least this module should support the OS that I'm actually using :)

**Comment by bartekrutkowski** [comment]
I was wondering, is the FreeBSD support coming or was this moved away from any realistic feature list?

**Comment by petems** [comment]
I just gave this a quick test, it works pretty much out the box for a basic installation :+1:

**Comment by ekohl** [comment]
A PR to support this is welcome, but given the age of this issue I'm going to close it for now. If a maintainer steps up, it'd be welcome though.
