### ISSUE TITLE
Should we include the puppet-jenkinstracking code?

### ISSUE THREAD

**Issue by rtyler** [voxpupuli/puppet-jenkins#110]
@kohsuke has been working on a [Puppet module](https://github.com/jenkinsci/puppet-jenkinstracking) to correspond with a [Puppet plugin for Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Puppet+Plugin) to close the loop on what files are where.

An example of usage from a manifest would be:

``` puppet
class foo {
    file {
        '/tmp/foo.war':
            source => "puppet:///modules/foo/foo.war"
    }

    track { '/tmp/foo2.war':
    }
```

My personal opinion is that this is acceptable to have in the "canonical Jenkins module for Puppet." I wanted to see what my co-maintainers thought.

//cc @jlambert121 @matthewbarr

**Comment by ekohl** [comment]
Given the age of this, I'm going to close this. Right now this module sees very little active contributions. If there's interest in this feature, a working patch should be provided. Until that time, I'm closing this.
