### ISSUE TITLE
Removes quotes from $JAVA_ARGS, otherwise java fails to start

### ISSUE THREAD

**Issue by flepoutre** [voxpupuli/puppet-jenkins#1110]
Hello, sorry but I don't understand why this bug is not fixed in master or last tag v5.0.0 ? (https://github.com/voxpupuli/puppet-jenkins/pull/940)

I have the issue too, for example :
`Aug  8 11:06:35 XXXXXX jenkins-slave-run[3711520]: Invalid initial heap size: -Xms2048m -Xmx2048m -Djava.io.tmpdir=/tmp
`

Thanks.

**Comment by flepoutre** [comment]
Hello, any feedback please ?
Thanks.

**Comment by kenyon** [comment]
It was fixed in commit 2a3e87327081700c3c17ecd2a8d41231652852da.

**Comment by flepoutre** [comment]
@kenyon Thanks for your feedback but I'm not sure to understand. Currently I used `jenkins::slave::java_args` parameter, now I must used `jenkins::slave::swarm_client_args parameter` ?
Thanks.

**Comment by flepoutre** [comment]
@kenyon Any news please 🙏  ? Thanks.

**Comment by flepoutre** [comment]
@kenyon Hello, if I replace `jenkins::slave::java_args` by `jenkins::slave::swarm_client_args` :

`-JAVA_ARGS="-Xms2048m -Xmx2048m -Djava.io.tmpdir=/tmp"`
`+OTHER_ARGS="-Xms2048m -Xmx2048m -Djava.io.tmpdir=/tmp"`

It doesn't work, I have this error when jenkins starting : 

`Sep 23 14:47:18 XXXXXXX jenkins-slave-run[3449441]: "-Djava.io.tmpdir=/tmp" is not a valid option
`
