### ISSUE TITLE
Error in plugin version check algo?

### ISSUE THREAD

**Issue by lseek** [voxpupuli/puppet-jenkins#192]
I seem to have stumbled on a bug in puppet-jenkins' version comparison logic for jenkins plugins - when I tried to install the "build-monitor-plugin" version "1.5+build.120" puppet-jenkins would always download the plugin (and restart jenkins).

On digging further I found that jenkins::plugin uses `$version` to construct a regexp `$search = "${name} ${version}(,|$)"` to determine whether or not a plugin occurs in the list of plugins. Therefore if `$version` contains special regexp characters (like "+") then the version will never be found in the plugin list because the special character will never be matched.

The solution to this, I suppose would be to quote `$version` when constructing `$search`. But since puppet doesn't give any direct function to do so I guess we'd need to jump into Ruby to do it:
`$search = inline_template('<%= Regexp.escape(@version) %>')` or something like that.

Is my understand correct?

Thanks.

PS: Puppet & Ruby noob.

**Comment by ekohl** [comment]
I'm closing this due to its age.
