### ISSUE TITLE
Add support for a custom JAVA_HOME

### ISSUE THREAD

**Issue by stevesaliman** [voxpupuli/puppet-jenkins#217]
I'd like to see a global variable in the Jenkins module that allows me to set a custom location for my JAVA_HOME, and for all the other modules to use that java when running commands.  Currently, I can add a `JENKINS_JAVA_CMD` to the config hash, and it does the right thing when it comes to starting the jenkins server, but the other commands, like the jenkins CLI, still try to use /usr/bin/java.

I'm currently looking at the code to see if I'd be able to add this feature, but as a Java developer, I'm having a little trouble getting the project setup in Intellij, or the tests to run from the command line.

**Comment by ekohl** [comment]
Given there has been no progress on this in the past years, I'm closing this. If this is still desired, a patch should be provided.
