### ISSUE TITLE
Ensure $::jenkins::localstatedir to Directory Breaks Filesystem's With Symlinked Mounts

### ISSUE THREAD

**Issue by malnick** [voxpupuli/puppet-jenkins#403]
On our deployment we mount an EBS volume in and symlink to /var/lib/jenkins. Ensuring this path to a directory in the module breaks that symlink. This is a sane default but could be improved by exposing $::jenkins::localstatedir file-type as a tunable parameter, giving the end-user more flexibility in the type of file that this should be. I'll submit a PR for this feature.

**Comment by esalberg** [comment]
@jhoblitt It looks like this issue can be closed?
