### ISSUE TITLE
JAVA_ARGS escaping issue

### ISSUE THREAD

**Issue by joshuaspence** [voxpupuli/puppet-jenkins#448]
I set the `java_args` parameter as follows:

```
$java_args = [
  '-Djdk.certpath.disabledAlgorithms="MD2, RSA keySize < 1024/jdk.certpath.disabledAlgorithms=MD2, RSA keySize < 512"',
]
```

This caused the `jenkins` service to fail because the `/etc/defaults/jenkins` file looked like this:

```
JAVA_ARGS="-Djdk.certpath.disabledAlgorithms="MD2, RSA keySize < 1024/jdk.certpath.disabledAlgorithms=MD2, RSA keySize < 512""
```

As a workaround, I changed `java_args` as follows:

```
$java_args = [
  "-Djdk.certpath.disabledAlgorithms='MD2, RSA keySize < 1024/jdk.certpath.disabledAlgorithms=MD2, RSA keySize < 512'",
]
```

**Comment by joshuaspence** [comment]
For what it's worth, this is a temporary workaround for https://issues.jenkins-ci.org/browse/JENKINS-31089.

**Comment by jhoblitt** [comment]
@joshuaspence What action are you suggesting?

**Comment by joshuaspence** [comment]
I'm not suggesting any action. I guess that we need to escape the parameter.

**Comment by ekohl** [comment]
Since #1035 the jenkins-run script is no longer managed in this module and part of the packages themselves. If they have an issue, the fix should be done upstream.
