### ISSUE TITLE
travis lint warnings

### ISSUE THREAD

**Issue by jhoblitt** [voxpupuli/puppet-jenkins#520]
The configuration changes made to `.travis.yml.` in #503 in order to add docker/acceptance tests into the test matrix are flagged by the travis gem's lint function.

```
Warnings for .travis.yml:
[x] in matrix.include section: unexpected key sudo, dropping
[x] in matrix.include section: unexpected key services, dropping
[x] in matrix.include section: unexpected key script, dropping
[x] in matrix.include section: unexpected key bundler_args, dropping
```

Presumably, these are bogus warnings that need to be resolved upstream.

/cc @petems

**Comment by jhoblitt** [comment]
Reported upstream: https://github.com/travis-ci/travis.rb/issues/376

**Comment by petems** [comment]
Yeah was gonna say, they're not being dropped because it's working! Very weird :sob:

**Comment by ekohl** [comment]
We've moved away from Travis CI.
