### ISSUE TITLE
puppet_helper.groovy throws java.lang.ClassNotFoundException: hudson.tasks.Mailer.UserProperty 

### ISSUE THREAD

**Issue by ekkaphoom** [voxpupuli/puppet-jenkins#633]
This issue is from release v1.7.0  when creating or updating user:
 **/usr/bin/java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://127.0.0.1:8080 -i /root/jenkins_cli_keyfile groovy /usr/lib/jenkins/puppet_helper.groovy create_or_update_user my_user slave@jenkins 'my_password' 'Jenkins slave user' ''**

ERROR: Unexpected exception occurred while performing groovy command.
java.lang.ClassNotFoundException: hudson.tasks.Mailer.UserProperty
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:692)

**Comment by phongsiri-tr** [comment]
I saw the same problem too. I workaround it by changing the class name to hudson.tasks.Mailer$UserProperty instead. 

`
loadClass("hudson.tasks.Mailer$UserProperty") 
`

**Comment by pgassmann** [comment]
Can you publish a new release with this fix?

**Comment by lawre** [comment]
@phongsiri-tr This did the trick for me.  Thanks for posting a workaround.

**Comment by esalberg** [comment]
@jhoblitt Can this issue be closed?
