### ISSUE TITLE
install jenkins 2.x

### ISSUE THREAD

**Issue by bmihaescu** [voxpupuli/puppet-jenkins#671]
Hi,

What should i set in order to install Jenkins 2.x using this module ?

Thanks

**Comment by jhoblitt** [comment]
jenkins 2.x will be installed by default.  You can specify the exact package version via the `verison` param. https://github.com/jenkinsci/puppet-jenkins/blob/master/manifests/init.pp#L177

**Comment by lawrenceong** [comment]
Does that mean that even though the documentation mentions that version 2 is not supported, it is still able to install it?

**Comment by ubellavance** [comment]
I just tested it and it installs fine.  I don't know about the rest of the module's functionalities, though.

**Comment by ubellavance** [comment]
I just tested a config change

``puppet
class { 'jenkins':
  executors => 0,
}
`` and it didn't work.

I get this error: `ERROR: This command is requesting the deprecated -remoting mode. See https://jenkins.io/redirect/cli-command-requires-channel`

**Comment by elconas** [comment]
Please see https://github.com/jenkinsci/puppet-jenkins/issues/749 ... this adds support for non remoting cli

**Comment by lmayorga1980** [comment]
:+1:
