### ISSUE TITLE
1.7.1 release?

### ISSUE THREAD

**Issue by mterzo** [voxpupuli/puppet-jenkins#678]
Any chance we can get a new minor release before 1.8?

**Comment by rtyler** [comment]
for why?

**Comment by mterzo** [comment]
Selfish reasons really.  There are a few PRs have gone in since 1.7.0 and would be nice to snag them off the the forge.

**Comment by ryayon** [comment]
Hi,

I agree with this mterzo.
Actually, I prefer writing puppet forge data instead of GitHub's in my Puppetfile.

In parallel, the README in the PuppetForge informs that Jenkins 2.x is not managed and that's not true anymore as far as I can read here.

**Comment by madAndroid** [comment]
I would have to agree with this - we currently have to pin to a particular ref in order to get changes that have recently gone into master; this obfuscates things somewhat, since it's difficult to tell by a shasum what point in to the repo we're currently pointed at. Librarian-puppet also allows version ranges to be defined, so that we can ensure only patch or minor releases get installed.

A regular release cycle would be an awesome thing to implement, but I appreciate that this might be something cumbersome to maintain.

**Comment by myoung34** [comment]
Main reason? jenkins-ci.org needs to be changed to jenkins.io
```
Error: Execution of '/bin/yum -d 0 -e 0 -y install jenkins' returned 1: No Presto metadata available for jenkins


Error downloading packages:
  jenkins-2.32.2-1.1.noarch: [Errno 256] No more mirrors to try.
Error: /Stage[main]/Jenkins::Package/Package[jenkins]/ensure: change from absent to present failed: Execution of '/bin/yum -d 0 -e 0 -y install jenkins' returned 1: No Presto metadata available for jenkins


Error downloading packages:
  jenkins-2.32.2-1.1.noarch: [Errno 256] No more mirrors to try.
```

```
Error: Execution of '/bin/curl https://updates.jenkins-ci.org/latest/credentials.hpi -o /tmp/credentials.hpi_20170216-6091-1odphz4 -fsSL --max-redirs 5' returned 7: curl: (7) Failed connect to archives.jenkins-ci.org:80; Operation now in progress
Error: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/Archive[credentials.hpi]/ensure: change from absent to present failed: Execution of '/bin/curl https://updates.jenkins-ci.org/latest/credentials.hpi -o /tmp/credentials.hpi_20170216-6091-1odphz4 -fsSL --max-redirs 5' returned 7: curl: (7) Failed connect to archives.jenkins-ci.org:80; Operation now in progress
```

```
http://pkg.jenkins-ci.org/redhat-stable/jenkins-2.32.2-1.1.noarch.rpm: [Errno 14] HTTP Error 302 - Found         0% [                                                                                                      ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.


Error downloading packages:
  jenkins-2.32.2-1.1.noarch: [Errno 256] No more mirrors to try.
```

**Comment by myoung34** [comment]
@jhoblitt can we get a release to update the domains per 6b0499bd048dbce48f3e644ca8e89ca602bd74ce

**Comment by rtyler** [comment]
@myoung34 The issue you experienced was a transient infrastructure error, it had nothing to do with the domains being used. updates.jenkins-ci.org still serves data (assuming the mirror network is behaving properly)

**Comment by myoung34** [comment]
Maybe. I redirected all jenkins-ci.org traffic to Jenkins.io and it all worked fine

**Comment by elconas** [comment]
Feedback of JenkinsCI was to switch to jenkins.io as jenkins-ci.org is legacy (twitter: https://twitter.com/jenkinsci/status/829620292779638784)
