### ISSUE TITLE
Puppetserver workaround still works?

### ISSUE THREAD

**Issue by vijaytripathi** [voxpupuli/puppet-jenkins#693]
I am using workaround adding cache in ruby's path in /etc/puppetlabs/puppetserver/conf.d/puppetserver.conf and also installing retries gem on puppetserver. Still on agent node keep hitting below error complaining about not able to find any of types
Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/jenkins_authorization_strategy: no such file to load -- puppet_x/jenkins at /etc/puppetlabs/code/environments/production/manifests/site.pp:100:3

**Comment by jhoblitt** [comment]
Is this a working environment that broke or a new installation?

**Comment by elconas** [comment]
It seems https://github.com/jenkinsci/puppet-jenkins/commit/dabd8e562848b1bb3eda981d4ccdaa6974504767 fixes the puppetserver compatibility issue.
