### ISSUE TITLE
puppet-jenkins 2.0

### ISSUE THREAD

**Issue by jhoblitt** [voxpupuli/puppet-jenkins#718]
There are number of changes I would like to make that should trigger a major API bump. Including:

- drop support for puppet 3.x (EOL'd at the end of 2016)
- drop support for ruby 2.0.0 (EOL'd for almost a year)
- remove all currently deprecated class/define params
- deprecate (ASAP) and make `jenkins::sysconfig` private - we need to resolve the conflict between `jenkins::port`, `jenkins::config_hash`, and user declared `jenkins::sysconfig` resources.
- make `jenkins::cli_helper private`
- ~~add puppet 4 type annotations to all public interfaces~~
- convert from erb -> epp

Thoughts/comments?

/cc @jenkinsci/puppet-jenkins-developers

**Comment by rtyler** [comment]
For the most part this looks fine; my only other request/desire would be to remove *as much if not all* of the clever file fuckery the module does. `jenkins::plugin` spends a lot of effort placing files in the right places.

If we can commit to requiring that a CLI SSH port must be present in order to configure Jenkins, at least on localhost, then we can make some positive and opinionated Groovy-based implementations which will ensure more correctness in configuration of the master.

**Comment by jhoblitt** [comment]
@rtyler I agree that `jenkins::plugin` is complex but I don't think anything in there is really blocking refactoring.  We could deprecate/remove the `pin` parameter since it is meaningless under jenkins 2.x and `timeout` doesn't do anything.  The other parameter we probably live without is `enabled` -- but there are likely some valid use cases for it.

**Comment by matonb** [comment]
Any reason why jenkins::plugin couldn't use the jenkins API ?

This from the command line for example installs the git plugin and all dependencies
````
url=http://jenkins.example.com:8080
plugin=git

curl -X POST \
  --data "<jenkins><install plugin='${plugin}@latest' /></jenkins>" \
  --header 'Content-Type: text/xml' \
  ${url}/pluginManager/installNecessaryPlugins
````

**Comment by jhoblitt** [comment]
It doesn't support versioning. The updatecenter json only contains metadata for the most recent release of all plugins. https://issues.jenkins-ci.org/browse/JENKINS-32793

**Comment by matonb** [comment]
Bother....

  Oh well never mind

**Comment by elconas** [comment]
Maybe you can use the user bootstrapping for Jenkins 2.0 and the new CLI code with username and password from https://github.com/jenkinsci/puppet-jenkins/pull/761 to setup the initial automation user. This way you can add support for:

* AD
* SAML
* LDAP
* OpenID
* Crowd and others

Also with init.groovy.d you can do ANYTHING you want. So no limits for this module anymore.

**Comment by elconas** [comment]
@jhoblitt I would even go further with the new CLI and everyting taking place now. 

* only support native providers (maybe wrap in defines) - this makes everything idempotent. (then this module is more a less a wrapper around the Jenkins Groovy API from puppet)
* only support Jenkins 2.54++ and 2.46.2++ (new CLI, username / password and SSH auth)
* Pluggable Authentication and Authorization Support
* use Groovy only (e.g. install plugins via plugin manager and not CLI, this fixes transitive resultion issues)
* provide external interface for external puppet code to call the Jenkins CLI (customer groovy skripts)
* provide interface to place bootstrap scripts in init.groovy.d by external puppet code (customer groovy skripts e.g. AD Setup) - maybe a simple concat ?

**Comment by vStone** [comment]
> * provide interface to place bootstrap scripts in init.groovy.d by external puppet code (customer groovy skripts e.g. AD Setup) - maybe a simple concat ?

I see no need to concat all groovy together, it seems even dangerous with variable names being re-used and overwritten. Groovy is not as strict as java and it could give people headaches. Maybe just a simple wrapper around file {} with some ordering

**Comment by vStone** [comment]
> It doesn't support versioning. The updatecenter json only contains metadata for the most recent release of all plugins. https://issues.jenkins-ci.org/browse/JENKINS-32793

On the other hand, if we download the plugins and upload them using the form, jenkins will get the additional dependencies and you can specify the exact version you want.

**Comment by kizzie** [comment]
So the way we handle versioning for plugins is to download the plugins to another place entirely and sym link the downloaded file (which has the version number in it) to the jenkins/plugin directory, rather than downloading them directly. This means we can roll back plugins quite easily. The current method doesn't seem to pay any attention to whether the version asked for has changed - only if it exists at all.

Not sure if this is an approach you're interested in taking though!

**Comment by ekohl** [comment]
In #966 there's plans for 3.0, which is really needed at this point.
