### ISSUE TITLE
Swarm 3.3 download URL doesn't exist

### ISSUE THREAD

**Issue by mmarseglia** [voxpupuli/puppet-jenkins#739]
in manifests/slave.pp the client jar file name is defined as:
`$client_jar = "swarm-client-${version}-jar-with-dependencies.jar"`

There is no swarm client 3.3 with that name at https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.3/
```
../
swarm-client-3.3-javadoc.jar        10-Feb-2017 08:20  80.47 KB
swarm-client-3.3-javadoc.jar.md5    10-Feb-2017 08:20  32 bytes
swarm-client-3.3-javadoc.jar.sha1   10-Feb-2017 08:20  40 bytes
swarm-client-3.3-sources.jar        10-Feb-2017 08:20  17.78 KB
swarm-client-3.3-sources.jar.md5    10-Feb-2017 08:20  32 bytes
swarm-client-3.3-sources.jar.sha1   10-Feb-2017 08:20  40 bytes
swarm-client-3.3.jar                10-Feb-2017 08:20  1.50 MB
swarm-client-3.3.jar.md5            10-Feb-2017 08:20  32 bytes
swarm-client-3.3.jar.sha1           10-Feb-2017 08:20  40 bytes
swarm-client-3.3.pom                10-Feb-2017 08:20  3.89 KB
swarm-client-3.3.pom.md5            10-Feb-2017 08:20  32 bytes
swarm-client-3.3.pom.sha1           10-Feb-2017 08:20  40 bytes
```

**Comment by SpencerMalone** [comment]
It seems that without announcing it in the changelogs, they removed the dependency-less jar and renamed the jar-with-dependencies to swarm-client-3.3.jar, so hopefully we just have to support that new URL name if version >= 3.3. See: https://issues.jenkins-ci.org/browse/JENKINS-42138

**Comment by jantman** [comment]
Yeah, that's what happened. I suppose the right way would be to change ``jenkins::slave::client_jar`` based on ``$version``, but for future-proofing, it would probably be good if that was exposed as a param as well.

**Comment by jantman** [comment]
It looks like #746 includes a code fix for this, but no test updates.

**Comment by jhoblitt** [comment]
This has indeed been fixed on master for sometime, so I'm going to close this ticket.
