### ISSUE TITLE
template path is required to be absolute

### ISSUE THREAD

**Issue by cova-fe** [voxpupuli/puppet-jenkins#768]
Hi All,
I'm having some trouble in understanding why the template path needs to be absolute:
job.pp line 41
` if $template { validate_absolute_path($template) }   `   

How can I use templates by providing an absolute path here?

**Comment by egouraud-claranet** [comment]
hi @cova-fe ,
you can workaround this by using config directly, 
    jenkins::job { 'MYJOB':
      ensure => present,
      config => template('mytemplate.erb'),
    }

**Comment by jhoblitt** [comment]
I'd guess that the `template` param exists to make it easy to call from hiera.  The validation does seem wrong...
