### ISSUE TITLE
apt-get update not run after jenkins repo added

### ISSUE THREAD

**Issue by patricklucas** [voxpupuli/puppet-jenkins#785]
On a clean install, I have to run puppet twice since the first run adds the jenkins apt repo but doesn't run apt-get update before trying to install it.

**Comment by patricklucas** [comment]
I solved this in my case with:

```
Apt::Source['jenkins'] -> Class['Apt::Update'] -> Package<|tag == $::jenkins::package_name|>
```

But that's clearly not generic enough to just add to the module.

**Comment by reist** [comment]
I have this rule, though also not sure how good an idea it is to include it in the module:
```class { 'apt': } -> Class['Apt::Update'] -> Package<|title != 'apt-transport-https'|>```
On all other server definitions, the Package has nothing inside, but for the Jenkins master the requirement in debian.pp made it a must.

**Comment by ekohl** [comment]
In https://github.com/voxpupuli/puppet-jenkins/issues/785 I started to prepare for this but in the end I'm not sure we can `contain apt::update` in `jenkins::repo::debian`.

**Comment by ekohl** [comment]
I believe this has been resolved in https://github.com/voxpupuli/puppet-jenkins/pull/821.
