### ISSUE TITLE
use get-job to ensure that exists, before create it

### ISSUE THREAD

**Issue by c4m4** [voxpupuli/puppet-jenkins#787]
every time that puppet agent run, I have an error, but I create the job from command line, it works

+++ /tmp/puppet-file20170810-14928-v875wx	2017-08-10 17:44:00.679981309 +0200
@@ -34,4 +34,3 @@
   </builders>
   <publishers/>
   <buildWrappers/>
-</project>

**Comment by jonhattan** [comment]
This one can be closed
