### ISSUE TITLE
Add a docker based acceptance test for Arch Linux

### ISSUE THREAD

**Issue by kBite** [voxpupuli/puppet-jenkins#797]
With #773 basic support for Arch Linux was introduced. In this issue I'd like to track creation of a docker based acceptance test for Arch Linux.

**Comment by ekohl** [comment]
In https://github.com/voxpupuli/puppet-jenkins/pull/1058 I took a stab at this, but it looks like the actual integration is broken. Please open a PR to fix this if anyone is interested, but for now I'm going to close this.
