### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by vijaytripathi** [voxpupuli/puppet-jenkins#816]
Do we have plans to support Puppet-Jenkins module for windows?

**Comment by jhoblitt** [comment]
See https://github.com/jenkinsci/puppet-jenkins/pull/466 I don't not know if anyone is actively working on this.

**Comment by ekohl** [comment]
Given there has been no indication of any progress on this, I'm going to close this. I also closed #466 and the same is still true: if there are patches that work, they'll be merged but until that happens I'm closing this.
