### ISSUE TITLE
Release a new version in Puppet Forge

### ISSUE THREAD

**Issue by beezly** [voxpupuli/puppet-jenkins#825]
The latest released version of this module in Puppet Forge is as old as the hills, and doesn't work with Jenkins 2.x, 

The master branch works fine with Jenkins 2. x and could do with a release so that people can use it more easily. Would that be possible?

**Comment by madAndroid** [comment]
Yes, please can someone do this?

We'd much prefer to be able to install from the forge, rather than git

**Comment by gepandz** [comment]
Yes! This is something that Puppet, Inc., needs to look into -- if a Forge module isn't updated for over a year, then it should probably lose its Approved flag. Either maintain the module or discontinue it -- leaving it in a weird zombie state isn't helpful.

Given that this module is doing some good things in good ways, I'm voting for just tagging something recent to update the Forge copy and make everyone happy. 😄 ... Because I know that the vote of a random Internet person carries so much weight. 😛

**Comment by SzymonLobocki** [comment]
+1

**Comment by jorhett** [comment]
At the very least, cut a new version tag in this code repo so we don't have to track HEAD.

**Comment by timbirk** [comment]
+1 - if your're running low on resource for some things like this perhaps you would like to take on a few community maintainers?

**Comment by matthewbarr** [comment]
@rtyler - I think you are the only one that can actually publish to the forge.  Anything we can do to help?

**Comment by haloflightleader** [comment]
WHAT?!@#$ The master branch works with Jenkins 2.x? I've been holding off on upgrading because I've been waiting for some semblance of compatibility and I was just about to ask whether Jenk 2.x will ever be supported.

Can I just get an unequivocal acknowledgement that the master branch really does work with Jenks 2? Thanks.

**Comment by haloflightleader** [comment]
+1 billion.

**Comment by beezly** [comment]
@haloflightleader - yes. The master branch works well with Jenkins 2.x.

**Comment by uhanisch** [comment]
+1

**Comment by hlaf** [comment]
+1

**Comment by wottah** [comment]
+1

**Comment by bastelfreak** [comment]
Hi @rtyler, are you interested in migrating this module to [vox pupuli](https://voxpupuli.org/)? The collective of puppeteers could help with the maintenance of this module and do regular releases. Of course you would keep write access to the repo.

**Comment by rtyler** [comment]
@bastelfreak Hey now there's a potential solution. gernally with GitHub I have found that whenever somebody pesters me for releases of things which are done in my hobby time, I mentally lose all motivation to work on those things.

This however is a constructive path forward to reduce the mental burned on me; does Forge have a pattern support for renaming modules yet?

**Comment by bastelfreak** [comment]
Yes the forge supports it! We (Vox Pupuli) requested this and Puppet implemented it a few months back. An example is this: https://forge.puppet.com/jfryman/nginx. Migration to Vox Pupuli takes a few minutes. Just ping is 24/7 in our IRC channel #voxpupuli on freenode and we can get this going.

**Comment by jonemo** [comment]
@bastelfreak @rtyler: I am excited to see this development! Apologies for nagging, but seeing the that the last comment is from a month ago I am curious if this transfer is still in progress? 

It looks like the Github repo has moved to the `voxpopuli` organization, and the repo URL has been updated to http://forge.puppetlabs.com/puppet/jenkins, but the module is not yet available at that URL.

**Comment by rnelson0** [comment]
@jonemo We are working on a new release in the puppet namespace. I believe there was interest in some sort of hangout to discuss outstanding PRs before that release, maybe doing some timeline plotting. You check join the Puppet slack and drop into #voxpupuli if you'd like to be part of the active convo, it's going to be a bit much for issues.

**Comment by jhoblitt** [comment]
Closing in favor of a new release checklist is #855

**Comment by ekohl** [comment]
Now really closing in favor of #855 :)
