### ISSUE TITLE
A Catalog type is required. at /etc/puppetlabs/code/modules/jenkins/manifests/cli.pp:46:37

### ISSUE THREAD

**Issue by cjfq** [voxpupuli/puppet-jenkins#826]
BINARIES
- Puppet: 5.3.3
- Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
- Distribution: Oracle Linux
- Module version: latest master branch of today

CODE
class pe::ci::jobs 
{
  jenkins::job { 'lint':
    config => template('pe/ci/lint.xml.erb')
  }

  jenkins::job { 'parse':
    config => template('pe/ci/parse.xml.erb')
  }

  jenkins::job { 'rspec':
    config => template('pe/ci/rspec.xml.erb')
  }

  jenkins::job { 'serverspec':
    config => template('pe/ci/serverspec.xml.erb')
  }

}

ERROR

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Illegal relationship operand, can not form a relationship with an Undef Value. A Catalog type is required. at /etc/puppetlabs/code/modules/jenkins/manifests/cli.pp:46:37 at /etc/puppetlabs/code/environments/production/modules/pe/manifests/ci/jobs.pp:14 on node jenkins
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by jhoblitt** [comment]
The `jenkins` class needs to be declared in the manifest.
