### ISSUE TITLE
Error: Invalid or corrupt jarfile /usr/lib/jenkins/jenkins-cli.jar

### ISSUE THREAD

**Issue by ZenonBaleron** [voxpupuli/puppet-jenkins#827]
I am seeing the following error:

Notice: /Stage[main]/Jenkins/Jenkins::Cli::Exec[set_num_executors]/Exec[set_num_executors]/returns: **Error: Invalid or corrupt jarfile /usr/lib/jenkins/jenkins-cli.jar**
Error: '/bin/cat /usr/lib/jenkins/puppet_helper.groovy | /usr/bin/java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://127.0.0.1:8080 groovy = set_num_executors 4' returned 1 instead of one of [0]
Error: /Stage[main]/Jenkins/Jenkins::Cli::Exec[set_num_executors]/Exec[set_num_executors]/returns: change from notrun to 0 failed: '/bin/cat /usr/lib/jenkins/puppet_helper.groovy | /usr/bin/java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://127.0.0.1:8080 groovy = set_num_executors 4' returned 1 instead of one of [0]

Executing manually shows the same:

\# /bin/cat /usr/lib/jenkins/puppet_helper.groovy | /usr/bin/java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://127.0.0.1:8080 groovy = set_num_executors 4
**Error: Invalid or corrupt jarfile /usr/lib/jenkins/jenkins-cli.jar**

The execution is on a CentOS 7.4 host using java-1.8.0-openjdk-headless-1.8.0.151-1.b12.el7_4.x86_64. This is using code cloned yesterday.

**Comment by jhoblitt** [comment]
That is a jvm error.  Try deleting the CLI jar file.

**Comment by jhoblitt** [comment]
This might have been an aspect of #782 but I'm going to go ahead and close it out.
