### ISSUE TITLE
Transfer to Vox Pupuli?

### ISSUE THREAD

**Issue by llowder** [voxpupuli/puppet-jenkins#828]
This module hasn't been updated in some time, and there seems to be a pretty high demand for updates and use of this module.

Can it be transferred to Vox Pupuli so it can still be maintained and updated?

**Comment by bastelfreak** [comment]
This is now in the Vox Pupuli namespace. Some open things:
* get https://github.com/voxpupuli/puppet-jenkins/pull/829 green
* make a new release
* sync labels
* deprecate the old one on the forge

**Comment by PierreR** [comment]
For information, the current dependency on puppetlabs/java (>= 1.0.1 < 2.0.0) for the latest released version of the module is quite annoying ...

**Comment by ekohl** [comment]
@PierreR is it annoying because it's not allowing the 2.x releases or is there another reason?

**Comment by PierreR** [comment]
Right it is annoying because I am already depending on puppet-java > 2

**Comment by jhoblitt** [comment]
@PierreR I don't see an existing open issue/PR to change the java module version constraint, perhaps you could open one?

**Comment by PierreR** [comment]
@jhoblitt I am not sure I understand what you mean ? The current master does allow `>= 1.0.1 < 3.0.0`  already : https://github.com/voxpupuli/puppet-jenkins/blob/master/metadata.json#L24

A new release would do the job.

**Comment by jhoblitt** [comment]
@PierreR Aw, I misunderstood the point of your comment.  I'm going to close this ticket out since the moduel has indeed been transferred.  @bastelfreak Perhaps there should be a new release checklist issue?  That is at least one previous one open as well along with poorly maintained milestones.

**Comment by juniorsysadmin** [comment]
https://github.com/voxpupuli/plumbing/issues/162
