### ISSUE TITLE
Acceptance tests related to plugin installations (or that require a plugin installation) are not failing/succeeding consistenly.

### ISSUE THREAD

**Issue by vStone** [voxpupuli/puppet-jenkins#839]
The current acceptance tests throw a couple of errors on the installation of plugins (besides the pending tests) but do not fail the build job. Looks like the missing dependencies on the first run might get installed in further tests.

**Comment by ekohl** [comment]
I got them green on Ubuntu (also in CI). For CentOS they work for me on a VM with vagrant_libvirt but in CI they fail. Not sure why. Might be docker related.
