### ISSUE TITLE
"Triage Meeting" on Monday 2018-02-19 @ 1600UTC

### ISSUE THREAD

**Issue by jhoblitt** [voxpupuli/puppet-jenkins#850]
We're planning to have a meeting next Monday @ 1600UTC to discuss items such as:

* a punch list of necessary tasks prior to making a new forge release
* major outstanding problems, such as reliable installation on Debian
* possible re-factoring of this module going forward

The meeting will be held on the standing Bluejeans "Community Pull Request Review & Bug Triage" conference.  https://bluejeans.com/280736660

Please feel free to suggest agenda items on this ticket.

**Comment by juniorsysadmin** [comment]
https://github.com/voxpupuli/plumbing/issues/162

**Comment by rnelson0** [comment]
This meeting occurred, #857 explores recurring meetings.
