### ISSUE TITLE
revert new CLI interface

### ISSUE THREAD

**Issue by jhoblitt** [voxpupuli/puppet-jenkins#854]
#752 added support for the "new" CLI jar interface that replaces the depreciated "remoting" protocol.  However, this seems to have broken the abliity to use the legacy remoting protocol.  This should be backed out before a new stable forge release.

**Comment by elconas** [comment]
Hello @jhoblitt, the Pull request referenced was authored by me. Can you explain the problem with it maybe I can fix.

**Comment by ekohl** [comment]
@elconas perhaps it's referring to https://github.com/voxpupuli/puppet-jenkins/issues/814

**Comment by hatless** [comment]
Curious why this is a blocker for a tagged release per #855. Surely a release that breaks the old (deprecated a year or so ago) remoting protocol  that we're not actually supposed to use anymore because security is better than a release that has not worked at all for nearly two years.

**Comment by ekohl** [comment]
Closing due to its age.
