### ISSUE TITLE
Jenkins user issue

### ISSUE THREAD

**Issue by techish1** [voxpupuli/puppet-jenkins#860]
This is with reference to #365 as per this issue must have been solved but it seems not

I'm configuring user as below

```puppet
class { 'jenkins':
     user => "anyuser",	
     group => "anygroup",	
     manage_user => true,	
     manage_group => true,	
  }
```

It does create user/group as above but jenkins still run as 'jenkins' user which is strange.

After digging further I found that /etc/sysconfig/jenkins file still has references to 'jenkins' user

```
## Type:        string
## Default:     "jenkins"
## ServiceRestart: jenkins
#
# Unix user account that runs the Jenkins daemon
# Be careful when you change this, as you need to update
# permissions of $JENKINS_HOME and /var/log/jenkins.
#
JENKINS_USER="jenkins"
```

Please fix or advise how I can make jenkins runs as "anyuser" instead of hardcoded "jenkins"

Thanks.

**Comment by techish1** [comment]
I was able to update jenkins user in sysconfig by passing config_hash like below but jenkins failed to start up and it somehow still creates jenkins user

class { 'jenkins':
user => $jenkins_user,
group => $jenkins_group,
manage_user => $jenkins_manage_user,
manage_group => $jenkins_manage_group,
config_hash => { 'JENKINS_USER' => { 'value' => $jenkins_user }, },
}

**Comment by ekohl** [comment]
I took the liberty of editing your comments to make them a bit more readable. See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by techish1** [comment]
Ok. Strangely jenkins user still gets created. Does yum install jenkins creates it?

Also, I need to chown /var/log/jenkins and /var/chache/jenkins in order to jenkins work under a different user. Can this be sorted out in jenkins module itself?

**Comment by ekohl** [comment]
@tthayer is correct. The RPM creates a user. I don't think there's anything else to do here though the `config_hash` could be interesting to fix in `jenkins::config`. Not sure if that'd work with Arch. @bastelfreak?

**Comment by tthayer** [comment]
I investigated RPM options and it doesn’t look like there is an easy way to override the user unless someone can find a spec file we can use to try to trick it. Even then it would take setting an environment variable and that isn’t something the Puppet package type supports passing in yet. It could be done by creating an environment file under /etc/yum/vars but that is even uglier as it would require creating and removing the var file around installing the RPM so we don’t break other package installs. 

Wrapping the “ensure => absent” block in an if block that compares the manage_user and user values to ‘jenkins’ and does the needful is probably the cleanest.

**Comment by ekohl** [comment]
Looking at the code, there's also more things that would degrade:

https://github.com/voxpupuli/puppet-jenkins/blob/0baf374bbc31086dab6606eef688e8f3d1220447/lib/puppet/x/jenkins/provider/cli.rb#L146-L151

I don't think this is something the module should support.
