### ISSUE TITLE
New tag? 

### ISSUE THREAD

**Issue by jfbarranco** [voxpupuli/puppet-jenkins#876]
Hi guys, latest tag 1.7.0 is 2 years old, why don't you tag more often?  e.g. every 6 months

I'd like this module and it works fine but I can't reference to "latest" and be exposed to changes that could be incompatible with the rest of my configuration.

Thanks!

**Comment by bastelfreak** [comment]
Hi @jfbarranco. We need to fix the (yet unknown) issue in https://github.com/voxpupuli/puppet-jenkins/pull/863. Afterwards we want to do a new release (and also release way more frequently). Happy help is highly appreciated.

**Comment by ekohl** [comment]
Closing in favor of #855
