### ISSUE TITLE
Duplicated declaration

### ISSUE THREAD

**Issue by isurugiu** [voxpupuli/puppet-jenkins#880]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:4.10.12
- Ruby: ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
- Distribution: CentOS Linux release 7.5.1804
- Module version: latest in master branch

## How to reproduce (e.g Puppet code you use)
Just running puppet agent -t
## What are you seeing

> root@ip-10-189-229-189 ~]# puppet agent -t
> Info: Using configured environment 'staging'
> Info: Retrieving pluginfacts
> Info: Retrieving plugin
> Info: Loading facts
> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Duplicate declaration: Jenkins::Plugin[structs] is already declared in file /etc/puppetlabs/code/environments/staging/modules/jenkins/manifests/config.pp:9; cannot redeclare at /etc/puppetlabs/code/environments/staging/modules/jenkins/manifests/plugins.pp:9 at /etc/puppetlabs/code/environments/staging/modules/jenkins/manifests/plugins.pp:9:3 on node ip-10-189-229-189.internal
> Warning: Not using cache on failed catalog
> Error: Could not retrieve catalog; skipping run

## What behaviour did you expect instead
Error free behaviour

**Comment by isurugiu** [comment]
Found the bug in my code.

Thanks.

**Comment by wdschei** [comment]
@isurugiu What was your bug?
I think I have the same one.
