### ISSUE TITLE
Unable to pass process properties to systemd

### ISSUE THREAD

**Issue by madelaney** [voxpupuli/puppet-jenkins#890]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.12
- Ruby: 2.1.9
- Distribution: Ubuntu
- Module version: 1.7.0

## How to reproduce (e.g Puppet code you use)
N/A - Not a bug.

## What are you seeing
N/A - Not a bug.

## What behaviour did you expect instead
I'd like to suggest we add the ability to pass Process properties to Systemd; i.e. LimitRTPRIO/LimitLOCKS. This would be a key/value pair that would be optional.

I was thinking about adding an optional hash to `jenkins::slave` that would pass said hash to `jenkins-slave.service.erb`.

If you'd be open to said change, let me know. I'll be happy to create a pull-request for said behavior.

**Comment by dhoppe** [comment]
@madelaney Sounds reasonable and we would be happy about a pull request.

**Comment by ekohl** [comment]
The suggested solution is systemd drop ins or a patch that implements this. Closing the issue for now.
