### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by pjfbashton** [voxpupuli/puppet-jenkins#891]
Are you planning to release new version of the module? 
1.7.0 is around two years old and its dependency on ancient version of puppetlabs/apt (< 3.0.0) is causing conflicts with many other modules.

**Comment by Dan33l** [comment]
A new release depends on https://github.com/voxpupuli/puppet-jenkins/pull/879. The tests currently don't work on modern ruby or puppet 5. Patches for that are highly appreciated. Feel free to join our IRC channel #voxpupuli on freenode or our slack channel at https://puppetcommunity.slack.com if you want to participate!

**Comment by janorn** [comment]
Considering that #879 was merged in January. Any plans for a release?

**Comment by skiedude** [comment]
2.0 released 12 hours ago, rejoice! https://github.com/voxpupuli/puppet-jenkins/releases/tag/v2.0.0
