### ISSUE TITLE
File jenkins-slave created with wrong owner under Darwin.

### ISSUE THREAD

**Issue by madelaney** [voxpupuli/puppet-jenkins#892]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.12
- Ruby: 2.3.7
- Distribution: Darwin (High Sierra)
- Module version:  1.7

## How to reproduce (e.g Puppet code you use)
`defaults.yaml`
```hiera
jenkins::slave::slave_user: build
jenkins::slave::slave_home: '/Users/build/.jenkins'
```

`site.pp`
```puppet
node default {
  include ::jenkins::slave
}
```

## What are you seeing

While deploying the catalog, some files are not respecting the fact that I'm overriding the Jenkins user. In my case it's coming from [slave](https://github.com/voxpupuli/puppet-jenkins/blob/master/manifests/slave.pp#L312-L313) lines 312-313.

This causes error as the user `jenkins` does not exist.

## What behaviour did you expect instead

I'd expect the files to get created with the correct user/group ownership. 

## Output log

```
Could not set 'file' on ensure: Could not find user jenkins at /etc/puppetlabs/code/thirdparty/jenkins/manifests/slave.pp:311 Wrapped exception: Could not find user jenkins
```

**Comment by dhoppe** [comment]
@madelaney I am confused. In version 1.7 the file ```slave.pp``` has only 299 lines. 
https://github.com/voxpupuli/puppet-jenkins/blob/v1.7.0/manifests/slave.pp

It looks more like the master branch is being used. In this case the user ```jenkins-slave``` will be created, but the file resource requires the user ```jenkins``` which has not been created. 

@bastelfreak It looks like the usage of ```defaults_user``` and ```slave_user``` are messed up somehow.
https://github.com/voxpupuli/puppet-jenkins/blob/master/manifests/slave.pp#L255
https://github.com/voxpupuli/puppet-jenkins/blob/master/manifests/slave.pp#L130 
https://github.com/voxpupuli/puppet-jenkins/blob/master/manifests/slave.pp#L297
https://github.com/voxpupuli/puppet-jenkins/blob/master/manifests/slave.pp#L309
