### ISSUE TITLE
repo parameter does not work

### ISSUE THREAD

**Issue by mlukowicz** [voxpupuli/puppet-jenkins#906]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:: 6.0.3
- Ruby: integrated
- Distribution: Debian Jessie Latest, Debian Stretch Latest
- Module version: latest

## How to reproduce (e.g Puppet code you use)
- require apt-transport-https to be installed on all hosts
- set apt source outside of jenkins module
- set jenkins::repo: false in hiera
- duplicate declaration of apt-transport-https appears error during puppet run

2nd issue:
- require all your hosts to run apt update on puppet pass
- add module to host
- observe dependency cycle during puppet run

In order to make it run you have to hard code $repo to false in init.pp and remove running apt update from all hosts

**Comment by mlukowicz** [comment]
Please disregard issue 2: last apt module update requires apt-transport-https to be installed.

1st issue still valid.

**Comment by vStone** [comment]
This sounds like it could be an issue with hiera rather than the puppet module. Could you provide a minimal repo that mimics this?

**Comment by ekohl** [comment]
This is solved in master.
