### ISSUE TITLE
remoting-cli setting removed in 2.165

### ISSUE THREAD

**Issue by witjoh** [voxpupuli/puppet-jenkins#918]
See also https://jenkins.io/blog/2019/02/17/remoting-cli-removed/

Since we don't have  a jenkins_version fact, maybe we could build in a check in **puppet_helper_global.groovy**  to ignore the remote-cli related actions when used in version higher then 2.165 ?
If this is an acceptable solution, I can do a PR for this.

**Comment by ekohl** [comment]
I would also be fine with dropping all support for the remoting cli and do a major version bump. Given it's been deprecated for 2 years and removed in future versions I wouldn't waste any time to support it.

**Comment by witjoh** [comment]
My mistake, error occured in one of my plugin-groovy scripts.  Mistook it for the puppet_helper.groovy one.
Closing this.

**Comment by witjoh** [comment]
@ekohl  I got a bunch of groovy scripts to configure jenkins-plugins.  I need to split them rom my jenkinks_profile module.  It could be usefull for other people also i Think.  Looks interesting for you?

**Comment by ekohl** [comment]
Without looking at the source: likely yes.

**Comment by witjoh** [comment]
@ekohl I will split the code into a separate module, and announce the link shortly ..
