### ISSUE TITLE
CSP Support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [voxpupuli/puppet-jenkins#927]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10
- Ruby: 2.0.0p648
- Distribution: CentOS 7.x
- Module version: latest master

## How to reproduce (e.g Puppet code you use)

Set the Java option in your yaml manifest like this:
```
jenkins::config_hash
  'JENKINS_JAVA_OPTIONS':
    value: |
        -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin allow-scripts allow-popups; default-src 'none'; img-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src *;"
```

## What are you seeing

```
Error: Could not find or load main class allow-same-origin
```

## What behaviour did you expect instead

Jenkins clean start.

## Output log

N/A

## Any additional information you'd like to impart

The java command line seems has an issue with system properties and spaces within their values.

**Comment by ekohl** [comment]
This has been refactored with the whole systemd rewrite.. Please reopen if this issue persists.
