### ISSUE TITLE
jenkins-slave-run script fails when JAVA_ARGS is set with multiple settings

### ISSUE THREAD

**Issue by witjoh** [voxpupuli/puppet-jenkins#939]
This is due to the quotes used in the script when adding $JAVA_ARGS to the $SLAVE_ARGS

`/usr/bin/java '-Xms3078m -Xmx3078m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=3000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false' -jar /opt/jenkins-slave/swarm-client-3.17.jar `
resulting in following error **Invalid initial heap size: -Xms3078m -Xmx3078m**

Removing the quotes solves the problem.  PR underway

**Comment by ekohl** [comment]
This was resolved in #939
