### ISSUE TITLE
Installed Credentials + Structs plugins are not pinned to a specific version

### ISSUE THREAD

**Issue by MattWatson-** [voxpupuli/puppet-jenkins#941]
## Problem

As stated in the title, the credentials and structs plugins are not pinned to specific versions and this is dangerous since they are installed by default

## Why
Many other plugins **_are_** pinned to a version and rely on these default plugins. So if the Jenkins server goes down and needs to be recreated, the default plugins might be installed to newer versions. The latest versions might be incompatible with the pinned plugins causing all sorts of problems. Unfortunately this happened to me recently.....

## How to solve

I think that it's fine to install the latest by default but there should be the option to override it via the init.pp but as a hash. In config.pp you should also use jenkins::plugins instead of jenkins::plugin

**Comment by witjoh** [comment]
@MattWatson- check https://github.com/witjoh/puppet-jenkins_plugin if you want to manage jenkins plugins wth puppet.
