### ISSUE TITLE
Jenkins-CLI cli.pp

### ISSUE THREAD

**Issue by Pajkanon** [voxpupuli/puppet-jenkins#944]
## How to reproduce (e.g Puppet code you use)
After version x.200 Jenkins there is no more jenkins-cli in the war file this can be solved by using wget/curl instead
## What are you seeing
Error extracting jenkins-cli
## What behaviour did you expect instead
No error?
## Any additional information you'd like to impart
in manifests/cli.pp i changed this too get it working:

    $jar = "${jenkins::libdir}/jenkins-cli.jar"
    $download_jar = "wget https://${::fqdn}/jnlpJars/jenkins-cli.jar -O /tmp/jenkins-cli.jar"
    $move_jar = "mv /tmp/jenkins-cli.jar ${jar}"
    $cli_tries = $jenkins::cli_tries
    $cli_try_sleep = $jenkins::cli_try_sleep

    # make sure we always call Exec[jenlins-cli] in case
    # the binary does not exist
    exec { 'check-jenkins-cli':
      command => '/bin/true',
      creates => $jar,
    }
    ~> exec { 'jenkins-cli' :
      command     => "${download_jar} && ${move_jar}",
      path        => ['/bin', '/usr/bin'],
      cwd         => '/tmp',
      refreshonly => true,
    }

**Comment by Pajkanon** [comment]
Added an example pull request for this also: https://github.com/voxpupuli/puppet-jenkins/pull/945/

**Comment by ekohl** [comment]
Do you have the exact version number? I still see it in `jenkins-2.204.2-1.1.noarch`

**Comment by genebean** [comment]
I am assuming this issue is what's causing me to run into the error below when upgrading from Jenkins 2.190.2 to 2.230... is that accurate?

```
Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns: mv: cannot stat ‘WEB-INF/jenkins-cli.jar’: No such file or directory
Error: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]: Failed to call refresh: 'jar -xf /usr/lib/jenkins/jenkins.war WEB-INF/jenkins-cli.jar && mv WEB-INF/jenkins-cli.jar /usr/lib/jenkins/jenkins-cli.jar && rm -rf WEB-INF' returned 1 instead of one of [0]
Error: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]: 'jar -xf /usr/lib/jenkins/jenkins.war WEB-INF/jenkins-cli.jar && mv WEB-INF/jenkins-cli.jar /usr/lib/jenkins/jenkins-cli.jar && rm -rf WEB-INF' returned 1 instead of one of [0]
Notice: /Stage[main]/Jenkins::Cli/File[/usr/lib/jenkins/jenkins-cli.jar]: Dependency Exec[jenkins-cli] has failures: true
Warning: /Stage[main]/Jenkins::Cli/File[/usr/lib/jenkins/jenkins-cli.jar]: Skipping because of failed dependencies
Warning: /Stage[main]/Jenkins::Cli/Exec[safe-restart-jenkins]: Skipping because of failed dependencies
Warning: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]: Skipping because of failed dependencies
Warning: /Stage[main]/Jenkins::Cli_helper/File[/usr/lib/jenkins/puppet_helper.groovy]: Skipping because of failed dependencies
Warning: /Stage[main]/Jenkins/Anchor[jenkins::end]: Skipping because of failed dependencies
Info: Class[Jenkins]: Unscheduling all events on Class[Jenkins]
Info: Stage[main]: Unscheduling all events on Stage[main]
```

**Comment by bogdankatishev** [comment]
Can confirm that we are also experiencing this problem on LTS v2.222.1

**Comment by craigwatson** [comment]
The fix for this is to download the Jar from Jenkins itself, rather than extracting it from the War.

Changing the `cmd` parameter of `jenkins-cli` to `/bin/wget http://localhost:8080/jnlpJars/jenkins-cli.jar -O /var/lib/jenkins/jenkins-cli.jar` worked for me.

If I have time, I'll try and get a PR up :)

**Comment by ekohl** [comment]
Be aware that there's already https://github.com/voxpupuli/puppet-jenkins/pull/967 and https://github.com/voxpupuli/puppet-jenkins/pull/945. I don't mind a mergeable PR that supersedes the other 2.

Also note that Puppet can already download files and there's no need for an exec with wget.
```puppet
file { '/var/lib/jenkins/jenkins-cli.jar'
  source => 'http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar'
}
```

**Comment by skluthe** [comment]
> Be aware that there's already #967 and #945. I don't mind a mergeable PR that supersedes the other 2.
> 
> Also note that Puppet can already download files and there's no need for an exec with wget.
> 
> ```puppet
> file { '/var/lib/jenkins/jenkins-cli.jar'
>   source => 'http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar'
> }
> ```

First off, I really appreciate the work you're doing on this project. I was wondering if there's a way to resolve this issue in the currently released version or do I need to fork it and then use my fork in my puppet projects?

**Comment by kenyon** [comment]
See #966 about a new release.
