### ISSUE TITLE
Ability to send in custom systemd parameters, or use a custom systemd template.

### ISSUE THREAD

**Issue by madelaney** [voxpupuli/puppet-jenkins#964]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.4.x
- Ruby: 2.5.7
- Distribution: Ubuntu (16.04 & 18.04)
- Module version: 2.0.0

## How to reproduce (e.g Puppet code you use)

N/A, not a bug.

## What are you seeing

I need to be able to raise the rtprio for my jenkins-slave.

## What behaviour did you expect instead

I would like to see either the ability to send in a custom hash of systemd properties, or the ability to use a custom systemd erb/pp template. I have the prior in a fork, but I'm not sure if people would prefer the template over properties.

## Output log

N/A

## Any additional information you'd like to impart

While I can set the rtprio limits for the user in `/etc/security`, but when the systemd service starts, the rtprio value is reset to zero.

The only way I've found to get this to work is by setting `LimitRTPRIO` within the systemd service file.

**Comment by cringdahl** [comment]
Will [drop-in files](https://forge.puppet.com/camptocamp/systemd#drop-in-files) work?

**Comment by ekohl** [comment]
Drop in files are indeed the best solution for this.

**Comment by igalic** [comment]
we could tag these kinda issues as questions (answered), would be nice for them to show up in the changelog

**Comment by ekohl** [comment]
I don't think a changelog is the right place for that. If anything, it should be in README or examples.
