### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jocelynthode** [voxpupuli/puppet-jenkins#966]
Hi,
I see it's been a while since a new release from this module has been released.
Could you please release a new version with the new commits please ?

If a new release is being blocked by something, could you tell what is blocking to see if this is something I can work on, so that we can move forward ?

**Comment by ekohl** [comment]
Currently the acceptance tests are failing. I've tried to take a look at it, but haven't had a lot of time for it. This is probably related to the CLI and there's a few PRs / issues around that as well. If the acceptance tests are green, I have no problem releasing a new version.

**Comment by JohnEricson** [comment]
I agree with this. I just upgraded to the latest released version 1.7.0 of the module for it to work on Puppet 5.5 but I still get the:
```
Server Error: Evaluation Error: Error while evaluating a Resource Statement, Apt::Source[jenkins]:
  has no parameter named 'key_source' 
  has no parameter named 'include_src'
```
error. This seems to be fixed in Git master so I will try that one, but it would be really nice if we can get a new release of this module.

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-jenkins/pull/981 at least made the test suite green on Ubuntu in Travis. On a libvirt VM it was also green on CentOS for me. Can't quite explain why yet, but I'd like to have green tests before we release.

I also started with going through some deprecations. However, I'm mostly working on it as a side project so progress is slow. Any help is appreciated.

**Comment by ekohl** [comment]
I've started to assign things to the 2.0.0 milestone.

**Comment by evgeni** [comment]
@ekohl shouldn't it be something higher than 2.0.0? 2.0.0 release exists :)

Anyways, a new release would be really appreciated, as Jenkins changed their signing keys (see e.g. the announcement on https://pkg.jenkins.io/redhat/) to https://pkg.jenkins.io/redhat/jenkins.io.key and the currently released module deploys the old key and then fails to install Jenkins :(

Changing just the key URL in the 2.0.0 release is sufficient to make this work, so maybe a 2.0.1 with that change only is a good intermediate solution?

**Comment by ekohl** [comment]
Well, it looks like I should have checked more. Looks like I should create a 3.0.0 milestone instead.

**Comment by genebean** [comment]
For any following along... #1000 is in progress (a rebase post-merge of other bits of the 3.0.0 milestone will still be needed).

**Comment by Fabian1976** [comment]
Maybe worth a bump? Could you release a newer version which has the `camptocamp/systemd` dependency removed (no longer maintained)?
