### ISSUE TITLE
Jenkins not installing on Centos 7 due to gpg key

### ISSUE THREAD

**Issue by Wade9320** [voxpupuli/puppet-jenkins#979]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.21
- Ruby: 
- Distribution: Centos7
- Module version: 2.0.0

## How to reproduce (e.g Puppet code you use)
Install a new server on Centos7

## What are you seeing
Jenkins doesn't install to fix have to do the following: 
```
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
```

We've tried many fresh installs and we still get the same issue. I've changed this manually in the module in our puppet code and the fix work. As the previous key in the 2.0.0 version is this:

https://pkg.jenkins.io/redhat/jenkins-ci.org.key

And it should be:

https://pkg.jenkins.io/redhat/jenkins.io.key

## What behaviour did you expect instead
Jenkins is just installed

**Comment by Wade9320** [comment]
@ekohl I have closed this #980 PR, but this issue still persists on version 2.0.0

**Comment by ekohl** [comment]
You need to use the git version which includes:
https://github.com/voxpupuli/puppet-jenkins/commit/67d219e07488626f3447e9c5aa15363749200e41#diff-bdd716adf278285c0d7f4a1651befad5

**Comment by igalic** [comment]
> You need to use the git version which includes:
> [67d219e#diff-bdd716adf278285c0d7f4a1651befad5](https://github.com/voxpupuli/puppet-jenkins/commit/67d219e07488626f3447e9c5aa15363749200e41#diff-bdd716adf278285c0d7f4a1651befad5)



ooooooor, we could make a new release

**Comment by Wade9320** [comment]
@igalic I agree I think a new release would be better

**Comment by Wade9320** [comment]
Also how do you specify a version like that in a PuppetFile?

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-jenkins/issues/966 is open for that.
