### ISSUE TITLE
function hiera_array is deprecated

### ISSUE THREAD

**Issue by koraz0815** [voxpupuli/puppet-jenkins#983]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.17.0
- Ruby: 2.0.0
- Distribution: CentOS Linux release 7.8.2003
- Module version: 2.0.0

## Output log
Puppet The function 'hiera_array' is deprecated in favor of using 'lookup'. See https://puppet.com/docs/puppet/6.17/deprecated_language.html

https://github.com/voxpupuli/puppet-jenkins/blob/c0eaac41e0e3218b5f832ba0980c372948bb03c8/manifests/slave.pp#L163
https://github.com/voxpupuli/puppet-jenkins/blob/c0eaac41e0e3218b5f832ba0980c372948bb03c8/manifests/slave.pp#L173
https://github.com/voxpupuli/puppet-jenkins/blob/c0eaac41e0e3218b5f832ba0980c372948bb03c8/manifests/slave.pp#L183

**Comment by ekohl** [comment]
A patch would be very welcome.

**Comment by drzombey** [comment]
I would like to fix it :)
