### ISSUE TITLE
Puppet enterprise error line 425  Could not find class ::java

### ISSUE THREAD

**Issue by gerbdla** [voxpupuli/puppet-jenkins#988]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Puppet Enterprise 2019.8.0
- Ruby:
- Distribution:
- Module version: tag:v2.0.0

## How to reproduce (e.g Puppet code you use)
class { "::jenkins":
    
  }

## What are you seeing
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Could not find class ::java for mmcs-dev-01.jpl.nasa.gov (file: /etc/puppetlabs/code/environments/mmcs/modules/jenkins/manifests/init.pp, line: 425, column: 5) on node test

## What behaviour did you expect instead
Expected to deploy

**Comment by igalic** [comment]
this module depends on puppetlabs/java
