### ISSUE TITLE
 undefined method strip

### ISSUE THREAD

**Issue by Elbandi** [voxpupuli/puppet-jenkins#990]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0
- Ruby: 2.5.1
- Distribution: ubuntu 18.04
- Module version: 2.0.1

## How to reproduce (e.g Puppet code you use)

```puppet
    include jenkins
```

## What are you seeing

``Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, undefined method `strip' for []:Array (file: /etc/puppet/code/modules/jenkins/manifests/plugin.pp, line: 115, column: 16) (file: /etc/puppet/code/modules/jenkins/manifests/config.pp, line: 6) on node ``

## What behaviour did you expect instead
install the jenkins

**Comment by Elbandi** [comment]
possible solution?
```default => split(strip($facts['jenkins_plugins']), ','),```

**Comment by igalic** [comment]
do you have puppetlabs/stdlib and the other dependencies installed?

**Comment by Elbandi** [comment]
There is a etc/puppet/code/modules/stdlib/lib/puppet/parser/functions/strip.rb file.

Other dependencies are exists too, only puppet version is less as requested, but i think it's irrelevant for this line.

**Comment by igalic** [comment]
the strip function in stdlib exists since 2.3.0: https://github.com/puppetlabs/puppetlabs-stdlib/commit/16eec26b0b2e671600ff048c54263adf032af5fd
which version do you have installed? and is it picked up in the environment that Jenkins runs in?

**Comment by Elbandi** [comment]
Oh, my fail :( 
there was an another strip function in my puppet, and override the stdlib's strip func. i removed the "pirate" strip.rb file, and now look like it works.

**Comment by igalic** [comment]
can you tell us which module that came from?

**Comment by Elbandi** [comment]
it's an own module. we use puppet long time ago, maybe someone wrote that "ghost" strip before we started to stdlib :/

**Comment by igalic** [comment]
thank you for the explanation!
